### ISSUE TITLE
[Android] read() and readFile() lead to "A resource failed to call close"

### ISSUE THREAD

**Issue by raphaelheinz** [birdofpreyru/react-native-fs#10]
Hi @birdofpreyru,

thanks for taking over the maintenance of this library. We appreciate your time and effort.

Currently, I am facing a problem that is also reproducible with the original library. I would like to read a large file (>20MB) in Android and for performance reasons I read it in chunks within a for-loop.

```javascript
import * as RNFS from '@dr.pogodin/react-native-fs';

const filepath="/storage/emulated/0/Android/data/com.testpackage.app/files/Download/largeFile.bin";

const size = (await RNFS.stat(filepath)).size;
const chunkSize = 32*1024;

for(let i = 0; i < size; i += chunkSize) {
  const data = await RNFS.read(filepath, chunkSize, i, 'base64');
  // do sth with data
}
```

Unfortunately a lot of Android system warnings are logged in the loop:
```A resource failed to call close.``` 

Are you aware of this problems? I do not feel comfortable releasing my app which contains tons of such warnings. Can I close the file manually to prevent this warning? Or do you recommend other techniques for my use case?

Thanks very much!

**Comment by birdofpreyru** [comment]
Hey @raphaelheinz , thanks for reporting.

> _a problem that is also reproducible with the original library_

Yeah... there are lots of minor inconsistencies and bugs in the original library, also inherited into my fork.

> _Are you aware of this problems?_

No, I haven't noticed it, but had no chance to carefully test everything either.

> _Can I close the file manually to prevent this warning? Or do you recommend other techniques for my use case?_

I guess, it just requires a fix in this function implementation for Android (and perhaps other functions may have the same issue):
https://github.com/birdofpreyru/react-native-fs/blob/fc86f093dc4e881fc1adbbc2623e7dad8325013d/android/src/main/java/com/drpogodin/reactnativefs/ReactNativeFsModule.java#L535-L555

:point_up: Looking at the code, and your warning, I guess it should close the file stream at function exit, but it never does.

**Comment by raphaelheinz** [comment]
Thanks for your input! I can confirm that this was indeed the issue. After closing the file within the Android native module, the warning has disappeared. If you like, I can submit a pull request after work.

**Comment by birdofpreyru** [comment]
> _If you like, I can submit a pull request after work :)_

It will be awesome if you do :)

**Comment by ISnowFoxI** [comment]
Hello, @birdofpreyru  it also doesn't close on ios as well. When I read chunks in a loop, the memory consumption just keeps on getting higher and higher. Sadly, I couldn't figure out how to close the file on my own.
