### ISSUE TITLE
[Android] `readDirAssets()` does not recognize as directories directories with names starting with `_` / or perhaps Android just does not bundle assets with such names --- should double-check it

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/react-native-fs#16]
See: https://github.com/birdofpreyru/react-native-static-server/issues/79#issuecomment-1770836921

**Comment by the-unknown** [comment]
Additionally, I found this:
https://stackoverflow.com/questions/9206117/how-to-workaround-autoomitting-fiiles-folders-starting-with-underscore-in

Might be an Android thing.

**Comment by the-unknown** [comment]
In my case it works if I add this to the `android{}`-section of the `build.gradle`

```gradle
android {
   //other code
    aaptOptions {
        ignoreAssetsPattern '!._'
    }

}
```

**Comment by birdofpreyru** [comment]
Ok, good to know, thus closing these issues as not a library fault.
