### ISSUE TITLE
Download Progress Callback does not get called on android

### ISSUE THREAD

**Issue by jobpaardekooper** [birdofpreyru/react-native-fs#31]
I recently moved over from the original RNFS to this library.

I am using the progress option on the `downloadFile` method to get `DownloadProgressCallbackResultT `. This was working properly before I migrated to this library. Now that I have made the switch it seems to only be working on iOS. On Android the callback never fires but the file downloads successfully.

**Comment by birdofpreyru** [comment]
Does not seem to work on iOS (new arch) either
