### ISSUE TITLE
iOS: Add a privacy manifest?

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/react-native-fs#32]
See: https://github.com/itinance/react-native-fs/issues/1232

**Comment by birdofpreyru** [comment]
Looking at this: https://github.com/zoontek/react-native-permissions/pull/861/files &mdash; I've missed to reference the manifest file in Podspec.

**Comment by raphaelheinz** [comment]
Hi @birdofpreyru,
when generating a privacy report in XCode, following error is displayed.

![privacypolicy](https://github.com/birdofpreyru/react-native-fs/assets/28300143/567e792d-be60-478d-8b28-3f2456d89b7b)

However, uploading to TestFlight works without any problems :)
I think the issue is that 1e75477 does not contain key NSPrivacyCollectedDataTypes. We should add it, even if it is empty...

If you like I can also open a PR.

**Comment by JOSEJ94** [comment]
Hi, thank you for all your effort on maintaining this package, you're truly heroes! 
Apologies for putting pressure on you all, but is this going to be released any time soon ? We're 2 days away from this becoming a blocker.

As a workaround for anyone reading this. Please add this patch to your projects. (It's the same change PR https://github.com/birdofpreyru/react-native-fs/pull/38 included)

```
diff --git a/node_modules/@dr.pogodin/react-native-fs/ios/PrivacyInfo.xcprivacy b/node_modules/@dr.pogodin/react-native-fs/ios/PrivacyInfo.xcprivacy
index c6976be..1e4b47e 100644
--- a/node_modules/@dr.pogodin/react-native-fs/ios/PrivacyInfo.xcprivacy
+++ b/node_modules/@dr.pogodin/react-native-fs/ios/PrivacyInfo.xcprivacy
@@ -26,5 +26,7 @@
 	<array/>
 	<key>NSPrivacyTracking</key>
 	<false/>
+	<key>NSPrivacyCollectedDataTypes</key>
+	<array/>
 </dict>
 </plist>
```

**Comment by birdofpreyru** [comment]
Ok @JOSEJ94 , I just released it as [v2.24.6](https://github.com/birdofpreyru/react-native-fs/releases/tag/v2.24.6). I did not know it was any urgent, thus wasn't thinking to release before I find time to do the library upgrade for RN@0.74 (#39).

**Comment by JOSEJ94** [comment]
Thank you so much! I'm not used to write in any repo, but in this case It was kind of urgent! You can get more information about this [here](https://developer.apple.com/news/?id=3d8a9yyh). I have installed it and tested it by submitting a build into testflight and can confirm it's no longer giving warnings

**Comment by birdofpreyru** [comment]
Great, @JOSEJ94 I take your words as it is confirmed to work alright, and thus this issue can be closed now.
