### ISSUE TITLE
Type interface differences from react-native-fs undocumented

### ISSUE THREAD

**Issue by angusryer** [birdofpreyru/react-native-fs#36]
Hi! Thanks for continuing to maintain this lib!

During a migration to your library (due to the new-ish Apple Privacy requirements), I noticed that the `ReadDirItem` type from `itinance/react-native-fs` is not present in this lib. It seems to have been changed to `ReadDirResItemT`.

So the statement in the readme, aside from the word "presumably", is not totally correct:

> v2.22.0 of this library is, presumably, a drop-in replacement for the latest (v2.20.0) release of the original, upstream [react-native-fs](https://github.com/itinance/react-native-fs) (beside the need to upgrade host project to the lates RN v0.73). It has matching functionality and API, with just a handfull of internal fixes, and a few additions.

I suppose it should be documented (along with other changes) for those migrating over. Not sure if any other interfaces have also changed.

**Comment by birdofpreyru** [comment]
Yes, I did append `T` to all type names. Sorry for not mentioning it in the README section you pointed to. I'll add it later.
