### ISSUE TITLE
Pending upgrade to RN@0.74

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/react-native-fs#39]
https://reactnative.dev/blog/2024/04/22/release-0.74

**Comment by inssein** [comment]
Just checking out this fork and running into this - curious if there is anything that actually needs to be done or just the version pinning adjustment?

**Comment by birdofpreyru** [comment]
I haven’t look at RN@0.74 yet. From previous experience, a proper upgrade to a new minor React version always requires some scaffolding & code updates.

**Comment by birdofpreyru** [comment]
Well... this upgrade turned out to be painless (still required to spend a few hours to smoke-test everything of all platforms / architectures :(
