### ISSUE TITLE
Permission denied (publickey)

### ISSUE THREAD

**Issue by Hisham546** [birdofpreyru/react-native-fs#4]
when i tried to install  the library npm install --save dr.pogodin/react-native-fs 
i'm getting this
npm ERR! command git --no-replace-objects ls-remote ssh://git@github.com/dr.pogodin/react-native-fs.git
npm ERR! git@github.com: Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.
npm ERR! 
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.

**Comment by birdofpreyru** [comment]
Have you missed `@` in front of the scope name? It should be `npm install --save @dr.pogodin/react-native-fs`.
