### ISSUE TITLE
[Android] `writeFile` not overwriting existing file

### ISSUE THREAD

**Issue by Eralyne** [birdofpreyru/react-native-fs#46]
It appears that the [issue presented in the original RNFS](https://github.com/itinance/react-native-fs/issues/700) is still present in this new fork. 

I'm trying to overwrite files by writing to the same file name in the same directory and it works perfectly fine on iOS but it doesn't on Android, which is reflective of how it is in the current RNFS.

I'm mainly wondering if this is something that you intend to keep as is or if it's a genuine issue that wasn't addressed yet.

**Comment by birdofpreyru** [comment]
Thanks @Eralyne , I did not know about this issue. `writeFile()` is important to me (#26), thus I'll try to test and fix it rather sooner than later.

**Comment by birdofpreyru** [comment]
Hey @Eralyne , I just tried to reproduce the bug within this library's Example App, by inserting `await writeFile(path, 'existing file content', 'ascii');` prior to the line 842 here:
https://github.com/birdofpreyru/react-native-fs/blob/89cb16915ad1f2234ed6ea4f7ffaccaa25973985/example/src/TestBaseMethods.tsx#L837-L854

expecting that if there is a problem with over-writing existing files by `writeFile()` the follow-up `readFile()` calls in that test will read unexpected content and fail the test; however, it does not fail for me, the test seems to pass fine. Tested in Emulator with both the latest Android 14 (SDK 34), and Android 10 (Q, SDK 29), which was mentioned in the original ticket.

Will you double-check me please? Am I missing something with my test, or with the Android version on which it should fail?

**Comment by Eralyne** [comment]
I'll double-check when I get the chance, that's interesting that it's not failing.

**Comment by Eralyne** [comment]
Hmm, I can't replicate it either. In our scenario, we're using base64 to save images. I tried doing that in your example code and it still seems to be working fine.

I'm going to go back to our codebase and see if I can adjust a few things to see if I can isolate the issue better. The weird thing is how closely it resembles the issue I linked originally. 

I'll send an update here as soon as I find something. It's a high priority on our end.

**Comment by Eralyne** [comment]
Looks like the overwrite is working fine. Our image is being cached by Android in a different way than iOS wherein it's not being refreshed when we need it to be.

Thanks for taking a look at this for us, sorry for wasting your time with a non-issue haha
