### ISSUE TITLE
RNFS.DocumentDirectoryPath not returning absolute path (Android)

### ISSUE THREAD

**Issue by jeremyengland** [birdofpreyru/react-native-fs#5]
Hi! I found an issue where both downloadFile and writeFile do not return absolute paths to the file after writing it... but only on Android. This causes issues on file read (the app cannot locate the file since the path is not absolute). The exact issue was surfaced when downloading/writing/reading an image, where the component worked fine on iOS but the image could not be found on Android (downloading/writing returned no errors, but I cannot prove that file exists).

Environment:
"react-native": "0.72.3",
"@dr.pogodin/react-native-fs": "^2.21.0-alpha.2"
MacBook 2019 (Intel)

Usage:
```
import { testPath, writeFile } from '../hooks/useFs'

const testWrite = async () => {
    const file = await writeFile(testPath, 'test.txt', 'testing, testing', 'utf8');
    console.log('file: ', file); // Logs the returned path of the file
  };
```

FS Hook:
```
import * as RNFS from '@dr.pogodin/react-native-fs';

const basePath = RNFS.DocumentDirectoryPath;

export const testPath = `${basePath}/test`;

export const writeFile = async (path: string, filename: string, content: string, encoding: RNFS.EncodingT) => {
  try {
    await makeFilePath(path);
    await RNFS.writeFile(path + '/' + filename, content, encoding);
    return path;
  } catch (e) {
    Promise.reject(`ERROR: writing ${content}, MSG: ${e}`);
  }
}
```

iOS Response: `file: /Users/firstnamelastname/Library/Developer/CoreSimulator/Devices/5B755636-CB5A-4044-93AD-B45C66B7B9DC/data/Containers/Data/Application/3F876A21-D1V4-444C-918E-08F724D93E57/Documents/test/test.txt`
Android Response: `file: /data/user/0/com.testapp/files/test/test.txt`
Expected Android Response: An absolute path similar to the iOS response.

**Comment by birdofpreyru** [comment]
Not sure I follow you… isn’t what you wrote you get on Android the absolute path to the directory? In the native code, I believe, it is set exactly the same as in the original library — https://github.com/birdofpreyru/react-native-fs/blob/affe286dd4588bf46b6b533ca9c7818202e7f02a/android/src/main/java/com/drpogodin/reactnativefs/ReactNativeFsModule.java#L70
thus, what it is wrong here?

**Comment by jeremyengland** [comment]
The response in my example is not the absolute path, since the absolute would start with `/Users/firstnamelastname/...`. I need a way to get the absolute path from my machine rather than the absolute path of the device, similar to the path returned by iOS. When reading from the path returned from Android, the file is not found.

Sorry if this doesn't make much sense!

**Comment by birdofpreyru** [comment]
Well, but the intent of `DocumentDirectoryPath ` is exactly to get the absolute path on the target device, that’s how it works now on Android… I’d even say it is less correct on iOS now… though, might be that’s got the simulator works there (uses the same root path as the host machine)

**Comment by birdofpreyru** [comment]
I see now what you wanna do, but I believe it is just not how the library supposed to work for that constant

**Comment by jeremyengland** [comment]
I will continue attempting to debug my exact issue. I would like to leave this issue open for the time being while I search for a solution in case it helps someone else.

**Comment by birdofpreyru** [comment]
Sure, just saying that it is not a bug, it is a feature request… if it is possible to get it for Android, it should be added as a new variable

**Comment by jeremyengland** [comment]
The solution to get the application to read the file was to prepend the file path with 'file://.' It now works on Android and iOS. Marking as closed.
