### ISSUE TITLE
Error: The package '@dr.pogodin/react-native-fs' doesn't seem to be linked.

### ISSUE THREAD

**Issue by ghumman** [birdofpreyru/react-native-fs#58]
I'm trying to run the app on android. The app builds fine but when I start the application on physical android device using `react-native run-android`. I get this error. 
```
 ERROR  Error: The package '@dr.pogodin/react-native-fs' doesn't seem to be linked. Make sure: 

- You rebuilt the app after installing the package
- You are not using Expo Go
, js engine: hermes 
```
I'm using following libraries: 
```
    "@dr.pogodin/react-native-fs": "^2.27.1",
    "react-native": "^0.74.3",
```

**Comment by birdofpreyru** [comment]
I guess, something is wrong with your app setup. I'd start with double-checking nothing in your dependencies tree uses the original `react-native-fs`; then try to build [Example App](https://github.com/birdofpreyru/react-native-fs/tree/master/example); then see what is different between the example app and your app setups.

**Comment by ghumman** [comment]
It was an old react native app. I spent few days bumping up `react-native-fs` and other libraries to latest versions but couldn't make it work. I gave up and created a brand new app with latest packages and moved my code to that app to make it work. After that `@dr.pogodin/react-native-fs` didn't give me any hard time. 

Thanks.
