### ISSUE TITLE
Windows support is broken since v2.29.0 / RN@0.76

### ISSUE THREAD

**Issue by birdofpreyru** [birdofpreyru/react-native-fs#76]

**Comment by birdofpreyru** [comment]
As of [v2.29.0](https://github.com/birdofpreyru/react-native-fs/releases/tag/v2.29.0) the upgrade is done for **Android**, **iOS**, **macOS**.

The upgrade for **Windows** is pending the release of [react-native-windows](https://github.com/microsoft/react-native-windows) v0.76.

**Comment by birdofpreyru** [comment]
It turns out, the upgrade to RN@0.76 for Windows is a large undertaking, which also requires to do the same upgrade in `react-native-static-server` and `react-native-webview` libraries in parallel. I can't spent on it as much time as necessary, unless somebody sponsors it; in particular considering that I am not using RN for Windows at all myself. Thus, the ticket has been renamed and put _On Hold_.

**Comment by pcprinz** [comment]
As mentioned in https://github.com/birdofpreyru/react-native-fs/issues/81#issuecomment-2495177234, The example app works for react-native-windows uwp-app with the old architecture in version 0.76.x. 
The cpp-app version with the new architecture need some work to be done. 

The mentioned dependency `react-native-static-server` only applies to the example app - and there only to the test for the `upload()` method. In that case I'd recommend to eiter temporary disable the test or get rid of the dependency at all in favor of making everything independent and get things done.
