### ISSUE TITLE
Android Build Fail

### ISSUE THREAD

**Issue by KartikDevarde2601** [birdofpreyru/react-native-fs#95]
### Using Expo 51  

:dr.pogodin_react-native-fs:compileDebugKotlin FAILED
e: file:///home/bioztwo/Documents/GitHub/sensorhub/node_modules/@dr.pogodin/react-native-fs/android/src/main/java/com/drpogodin/reactnativefs/ReactNativeFsPackage.kt:23:47 None of the following functions can be called with the arguments supplied: 
public constructor ReactModuleInfo(p0: String!, p1: String!, p2: Boolean, p3: Boolean, p4: Boolean, p5: Boolean) defined in com.facebook.react.module.model.ReactModuleInfo
public constructor ReactModuleInfo(p0: String!, p1: String!, p2: Boolean, p3: Boolean, p4: Boolean, p5: Boolean, p6: Boolean) defined in com.facebook.react.module.model.ReactModuleInfo

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':dr.pogodin_react-native-fs:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details

### React-Native-Info
System:
  OS: Linux 6.8 Ubuntu 24.04.1 LTS 24.04.1 LTS (Noble Numbat)
  CPU: (12) x64 11th Gen Intel(R) Core(TM) i5-11500 @ 2.70GHz
  Memory: 7.66 GB / 15.31 GB
  Shell:
    version: 5.2.21
    path: /bin/bash
Binaries:
  Node:
    version: 20.16.0
    path: ~/.nvm/versions/node/v20.16.0/bin/node
  Yarn:
    version: 1.22.22
    path: ~/.nvm/versions/node/v20.16.0/bin/yarn
  npm:
    version: 10.8.1
    path: ~/.nvm/versions/node/v20.16.0/bin/npm
  Watchman:
    version: 4.9.0
    path: /usr/bin/watchman
SDKs:
  Android SDK:
    Android NDK: 25.1.8937393
IDEs:
  Android Studio: AI-242.23339.11.2421.12700392
Languages:
  Java:
    version: 17.0.11
    path: /home/bioztwo/.sdkman/candidates/java/current/bin/javac
  Ruby: Not Found
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.74.5
    wanted: 0.74.5
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: Not found
  newArchEnabled: false

**  "@dr.pogodin/react-native-fs": "^2.28.1",**

**Comment by birdofpreyru** [comment]
`@dr.pogodin/react-native-fs@2.28.1` was intended for `react-native@0.75.3`; it seems you have troubles running it for RN@0.74.5 &mdash; perhaps, that is the problem.
